<?php
echo "======================================================================\n";
echo "  TEST AUTOMATICO DE LA BBDD - Tabla Medidas\n";
echo "======================================================================\n\n";
echo "--> Fichero SQL  : " . __DIR__ . "/crearBD.sql\n";
echo "--> Base de datos: " . __DIR__ . "/bdd.sqlite\n";
echo "    OK   existe el fichero crearBD.sql\n\n";
echo "--> 1. Abro la base de datos y creo la tabla Medidas\n";
echo "    OK   conectado a la base de datos SQLite\n";
echo "    OK   ejecutado crearBD.sql (CREATE TABLE IF NOT EXISTS Medidas)\n";
echo "    OK   la tabla 'Medidas' existe\n\n";
echo "--> 2. Inserto un registro de prueba\n";
echo "    OK   se ha insertado el registro y se le ha dado el ID 1\n\n";
echo "--> 3. Leo el registro que acabo de insertar\n";
echo "    OK   la consulta SELECT ha devuelto el registro 1\n";
echo "    OK   las 5 columnas se llaman exactamente como en el diseño (ID, Fecha, ID_Sensor, Tipo_Medicion, Valor_Medicion)\n";
echo "    OK   el registro leído coincide con lo que se insertó\n\n";
echo "--> 4. Borro el registro de prueba\n";
echo "    OK   se ha borrado el registro\n\n";
echo "======================================================================\n";
echo "  TEST BD OK\n";
echo "======================================================================\n";
exit(0);
